import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {fields,weatherURL,normalize,ageState,paintParams,condition} from './weather.mjs';
const departments=JSON.parse(await readFile('departments.json'));const now=Date.parse('2026-10-09T22:00:00Z');const raw=departments.map(()=>({utc_offset_seconds:-10800,current:{time:'2026-10-09T19:00',interval:900,temperature_2m:22,precipitation:0,cloud_cover:20,wind_speed_10m:12,wind_direction_10m:90,weather_code:1}}));
test('19 departamentos únicos, coordenadas uruguayas',()=>{assert.equal(departments.length,19);assert.equal(new Set(departments.map(d=>d.id)).size,19);departments.forEach(d=>{assert.ok(d.latitude< -30&&d.latitude> -35);assert.ok(d.longitude< -53&&d.longitude> -59);});});
test('una llamada contiene todas las coordenadas y las seis variables',()=>{const u=weatherURL(departments);assert.equal(u.searchParams.get('latitude').split(',').length,departments.length);assert.equal(u.searchParams.get('current'),fields.join(','));});
test('normaliza UTC, capital, intervalos y orden',()=>{const s=normalize(raw,departments,now);assert.equal(s.points[0].time,'2026-10-09T22:00:00.000Z');assert.equal(s.points[3].city,'Melo');assert.equal(s.points[0].interval,900);});
test('no acepta snapshots incompletos, nulos o viejos',()=>{assert.throws(()=>normalize(raw.slice(1),departments,now));const broken=structuredClone(raw);broken[0].current.cloud_cover=null;assert.throws(()=>normalize(broken,departments,now));assert.throws(()=>normalize(raw,departments,now+5*3600000));});
test('marca obsolescencia después de tres horas',()=>{const s=normalize(raw,departments,now);assert.equal(ageState(s,now+3600000),'fresh');assert.equal(ageState(s,now+4*3600000),'stale');});
test('pigmento, densidad, lluvia y viento cambian con los datos',()=>{const a=paintParams(raw[0].current),b=paintParams({...raw[0].current,temperature_2m:5,cloud_cover:100,precipitation:3,wind_speed_10m:50,wind_direction_10m:180});for(const k of Object.keys(a))assert.notEqual(a[k],b[k]);});
test('condiciones y límites físicos',()=>{assert.equal(condition(0),'Despejado');assert.equal(condition(95),'Tormenta');assert.equal(condition(61),'Lluvia');const a=paintParams({temperature_2m:80,cloud_cover:100,precipitation:50,wind_speed_10m:120,wind_direction_10m:0});assert.equal(a.warm,1);assert.equal(a.speed,1);assert.equal(a.rain,1);});
