import assert from 'node:assert/strict';
import {chromium} from '@playwright/test';import {createServer} from 'node:http';import {readFile,mkdir} from 'node:fs/promises';import path from 'node:path';
await mkdir('test-output',{recursive:true});
const server=createServer(async(req,res)=>{try{const f=req.url==='/'?'index.html':req.url.split('?')[0].replace(/^\/intemperie\//,'/').slice(1);const data=await readFile('dist/'+f);const ext=path.extname(f);res.setHeader('Content-Type',({'.html':'text/html','.mjs':'text/javascript','.json':'application/json','.css':'text/css','.woff2':'font/woff2'})[ext]||'application/octet-stream');res.end(data);}catch{res.statusCode=404;res.end('404');}}).listen(8765);
const browser=await chromium.launch({executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome-stable',headless:true,args:['--no-sandbox']});
try{
const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
for(const width of [320,390,1440]){await page.setViewportSize({width,height:width>800?1000:844});await page.goto('http://localhost:8765/');await page.waitForSelector('.painting');await page.evaluate(()=>document.fonts.ready);await page.locator('.art').first().click();await page.waitForFunction(()=>document.querySelector('.data').hidden===false);await page.screenshot({path:`test-output/real-${width}.png`,fullPage:width<800});console.log('layout',width,await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,cards:document.querySelectorAll('.painting').length,buttons:[...document.querySelectorAll('button:not(.mini)')].every(b=>{const r=b.getBoundingClientRect();return r.width>=44&&r.height>=44}),open:document.querySelector('.art').getAttribute('aria-expanded')})));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('.painting').count(),19);if(width===390){await page.getByRole('button',{name:'Ir a Rivera',exact:true}).click();await page.waitForTimeout(700);assert.equal(await page.getByRole('button',{name:'Ir a Rivera',exact:true}).getAttribute('aria-current'),'true');console.log('Rivera selected',await page.getByRole('button',{name:'Ir a Rivera',exact:true}).getAttribute('aria-current'));await page.locator('#gallery').focus();await page.keyboard.press('ArrowRight');await page.waitForTimeout(700);assert.equal(await page.locator('.mini[aria-current=true]').getAttribute('aria-label'),'Ir a Rocha');console.log('keyboard selected',await page.locator('.mini[aria-current=true]').getAttribute('aria-label'));await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>document.getAnimations().every(a=>a.playState==='paused')),true);console.log('reduced-motion paused',await page.evaluate(()=>document.getAnimations().every(a=>a.playState==='paused')));}}
await page.setViewportSize({width:390,height:844});await page.goto('http://localhost:8765/404.html');await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:'test-output/real-404.png'});
assert.deepEqual(errors,[]);console.log('JS errors',errors);
}finally{await browser.close();server.close();}
